### ISSUE TITLE
Build error with `WixToolset.UI.wixext`

### ISSUE THREAD

**Issue by Coloryr** [oleg-shilo/wixsharp#1473]
```
生成开始于 16:38...
1>------ 已启动生成: 项目: ColorMC.Setup.Wix, 配置: Debug Any CPU ------
1>ColorMC.Setup.Wix -> E:\code\ColorMC\src\ColorMC.Setup.Wix\bin\Debug\net472\win-x86\ColorMC.Setup.Wix.exe
1>
1>----------------------------------------------------------
1>
1>Wix project file has been built: E:\code\ColorMC\src\ColorMC.Setup.Wix\colormc-x64.wxs
1>
1>Compiling colormc-x64.wxs
1>Source base directory: E:\code\ColorMC\src\ColorMC.Setup.Wix
1>wix.exe : error WIX0144: The extension 'WixToolset.UI.wixext' could not be found. Checked paths: WixToolset.UI.wixext, C:\Users\40206\.wix\extensions\WixToolset.UI.wixext\5.0.0-rc.1\wixext4\WixToolset.UI.wixext.dll
1>
1>----------------------------------------------------------
1>
1>Wix project file has been built: E:\code\ColorMC\src\ColorMC.Setup.Wix\colormc-x64-aot.wxs
1>
1>Compiling colormc-x64-aot.wxs
1>Source base directory: E:\code\ColorMC\src\ColorMC.Setup.Wix
1>wix.exe : error WIX0144: The extension 'WixToolset.UI.wixext' could not be found. Checked paths: WixToolset.UI.wixext, C:\Users\40206\.wix\extensions\WixToolset.UI.wixext\5.0.0-rc.1\wixext4\WixToolset.UI.wixext.dll
1>E:\code\ColorMC\src\ColorMC.Setup.Wix\ColorMC.Setup.Wix.csproj(36,5): error MSB3073: 命令“cd .\
1>E:\code\ColorMC\src\ColorMC.Setup.Wix\ColorMC.Setup.Wix.csproj(36,5): error MSB3073: set ide=true
1>E:\code\ColorMC\src\ColorMC.Setup.Wix\ColorMC.Setup.Wix.csproj(36,5): error MSB3073: "E:\code\ColorMC\src\ColorMC.Setup.Wix\bin\Debug\net472\win-x86\ColorMC.Setup.Wix.exe"”已退出，代码为 -1。
1>已完成生成项目“ColorMC.Setup.Wix.csproj”的操作 - 失败。
========== 生成: 0 成功，1 失败，6 最新，0 已跳过 ==========
========== 生成 于 16:38 完成，耗时 04.920 秒 ==========

```
This issue start in yesterday(2024.3.9)

My CI in here
[Fail](https://github.com/Coloryr/ColorMC/actions/runs/8212713176)
[Done](https://github.com/Coloryr/ColorMC/actions/runs/8182073296)

**Comment by VietBuiHa** [comment]
I'm getting the same error, I think it is related to the newest wix release 5.0.0-rc.1 yesterday.
https://github.com/orgs/wixtoolset/discussions/8023

**Comment by oleg-shilo** [comment]
Yes the problem is caused by the defective 5.0.0-rc.1 release.

Specifically, by the fact that WiX v4.0 pulls WiX v5.0 pre-releases packages. In this case WxToolset.UI.wixext.

The package is defective as it has no files:
![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/d934aa7c-e18b-4d40-8eeb-efd6d48169c9)

Though given if the files were there they most likely would not be compatible with the v4.0 compiler.

The problem needs to be fixed by the WiX team.

Now, what you guys can do? There is a trick.
WixSharp is always using the latest extension available on the system. Thus it's enough to remove `5.0.0-rc.1` folder and ensure the older version of the extension (e.g. 4.0.2) is installed.

In my case (see the screenshot) I have the old version from my previous builds. But if it is a new environment, installing a specific version can be a challenge. 

`wix.exe extension add -g WixToolset.UI` always installs the latest package (extension) version available on the package repository. And I do not see any option in CLI on how to target a specific version. This is something that you can try to resolve. If you do, please share it here.

**Comment by oleg-shilo** [comment]
Just to help your further troubleshooting...

`wix extension add -g -v 4.0.2 WixToolset.UI.wixext` installs the latest version of the package but not the one I specified. CLI help is completely silent about how to target specific versions. Oh, dear...

**Comment by oleg-shilo** [comment]
If you cannot find the way then you can always get the required version from NuGet:
```
dotnet add package WixToolset.UI.wixext --version 4.0.2
```
and then simply copy the package in the `%userprofile%\.wix\extensions` folder. You see, WiX reused NuGet packages but it does not incorporate nuget goodness like specific versions, recognizing pre-releases, or compatibility algorithms. Again, oh, dear...

**Comment by Coloryr** [comment]
> If you cannot find the way then you can always get the required version from NuGet:
> 
> ```
> dotnet add package WixToolset.UI.wixext --version 4.0.2
> ```
> 
> and then simply copy the package in the `%userprofile%\.wix\extensions` folder. You see, WiX reused NuGet packages but it does not incorporate nuget goodness like specific versions, recognizing pre-releases, or compatibility algorithms. Again, oh, dear...

How to do this in github action?

**Comment by oleg-shilo** [comment]
You have a few options.
You can have a step where you create a dummy project add the package to it. This will download the package in the global packages store `%userprofile%\.nuget\packages\wixtoolset.ui.wixext`. Now you can copy it to WiX packages store.

```
dotnet new console
dotnet add package WixToolset.UI.wixext --version 4.0.2
md "%userprofile%\.wix\extensions\wixtoolset.ui.wixext\4.0.2"
xcopy "%userprofile%\.nuget\packages\wixtoolset.ui.wixext\4.0.2\wixext4" "%userprofile%\.wix\extensions\wixtoolset.ui.wixext\4.0.2\wixext4\" /S
```

That's it. So you can just add a batch file step in your CI and execute it before the WixSharp build.

**Comment by Coloryr** [comment]
```
    - name: Install WiX Toolset
      run: |
        choco install wixtoolset
        dotnet tool install --global wix
        dotnet new console
        dotnet add package WixToolset.UI.wixext --version 4.0.2
        md "%userprofile%\.wix\extensions\wixtoolset.ui.wixext\4.0.2"
        xcopy "%userprofile%\.nuget\packages\wixtoolset.ui.wixext\4.0.2\wixext4" "%userprofile%\.wix\extensions\wixtoolset.ui.wixext\4.0.2\wixext4\" /S
```
Is right?

**Comment by VietBuiHa** [comment]
Yep, it's frustrating, it just literally breaks everyone's builds.
The following commands work for me

`dotnet tool install --global wix --version 4.0.4`
`wix extension add -g WixToolset.UI.wixext/4.0.4`

**Comment by oleg-shilo** [comment]
Great. Thank you fro sharing.

> wix extension add -g WixToolset.UI.wixext/4.0.4

That was that magic syntax that WiX team did not share with us, unfortunately.

With this tric you don't need to deal with the nuget packages just have a single step ` wix extension add -g WixToolset.UI.wixext/4.0.4` and you are good

**Comment by oleg-shilo** [comment]
Since it's been more than 3 weeks and WiX team has not patched/removed the broken extension from nuget,.org, 
I decided to handle this problem in WiX sharp. 

Thus now you can request building your msi with a specific version of the extension in question. For the problem we are discussing the work around will be as below:

```C#
WixExtension.UI.PreferredVersion = "4.0.4";
. . .
project.BuildMsi();
```

I have also updated the compiling algorithm and now it warns you if accidentally you are trying to build your msi with a broken version of `WixToolset.UI.wixext`. 

![image](https://github.com/oleg-shilo/wixsharp/assets/16729806/9bccb5ba-f64a-4888-a15f-25e02a3c0b93)

I will release this enhancement in a day or two.

**Comment by Coloryr** [comment]
That is good

**Comment by oleg-shilo** [comment]
Done. You can find the update in the latest v2.1.5 release.

Note, that this change was implemented to specifically avoid the use of the defective version of WiX extension (WixToolset.UI.wixext v5.0.0-rc.1). 

While this work can be used to target a specific version of any extension in general, this workaround can be removed when WiX team releases the next version of this extension.

This is how you can target a specific version of an extension:

```C#
WixExtension.UI.PreferredVersion = "4.0.4"; // or any other working version
. . .
project.BuildMsi();
```

**Comment by Psychlist1972** [comment]
@oleg-shilo FYI. Just ran into this today with a brand new WixSharp WPF v4 project. The install of 4.0.4 manually from the command line fixed it. Before that, I was getting exactly the same error as OP. I had been using WiX v4 for the past year+ and just found WixSharp and wanted to give it a try.

So this problem is still a thing, unfortunately.

**Comment by oleg-shilo** [comment]
Hi @Psychlist1972, 

The WiX team has fixed this problem in the later WiX 5 proper (not `-pre`) release.
I suggest you simply update your wix installation to the latest and let me know if it addresses the issue. I expect it does.

I just retested it against my 

![Image](https://github.com/user-attachments/assets/02af12e6-4160-48e4-96ed-b935f45c4e3b)

**Comment by oleg-shilo** [comment]
I also just tested the very latest version WiX v5.0.2 and it is OK too:

![Image](https://github.com/user-attachments/assets/cc63e6ad-43b5-4c03-acf8-de5c4dd4e583)

Pete, since you just started with WixSharp I highly recommend using VS templates for WixSharp. This is the best way to avoid compatibility problems. 
You can add the WixSharp templates from the VS extension manager as with any other project templates.

**Comment by Psychlist1972** [comment]
> I also just tested the very latest version WiX v5.0.2 and it is OK too:

I'll check to see what toolset version I was running, but installing 4.0.4 fixed it. I don't recall ever installing any v5.

> Pete, since you just started with WixSharp I highly recommend using VS templates for WixSharp. This is the best way to avoid compatibility problems. You can add the WixSharp templates from the VS extension manager as with any other project templates.

Yes, that's what I started with. I took the WixSharp WPF template and tried compiling it as-is.

**Comment by oleg-shilo** [comment]
Great, then you are all set.

>I don't recall ever installing any v5.

I do suggest that you move to the latest WiX as there were some fixes since Wix4. And if I recall right the important ones.
And just to avoid possible confusion I have renamed all Wix4 templates to Wix. 

`WixSharp Managed Setup (WiX4)` -->  `WixSharp Managed Setup`

Since Wix4 in the context of WixSharp represents the technology stream not a specific version of the framework. It's like .NET Core 3.0 and .NET 8.0 is the same technology stream but .NET 4.8 is not (it's .NET Framework)

**Comment by TimLudwig5400** [comment]
just in case anyone is having an issue creating the MSI file with Wixsharp with the Toolset 5.0.2 (I was just using Default code which works fine on my other machine but I couldn't remember what I did to fix the issue on that machine), running this command fixed it:

wix extension add -g WixToolset.UI.wixext/5.0.2

Honestly it was a shot in the dark since nothing else seemed to get it to work but it works now. I had already run the command

dotnet tool install --global wix --version 5.0.2

but it would not build. it kept complaining about the <Target Name="PostBuild" AfterTargets="PostBuildEvent"> tag in the csproj file which I believe tells it where to build the MSI file in the default code in the project. 

Just thought I would post this in case someone else has the same issue with 5.0.2.

Tim

**Comment by oleg-shilo** [comment]
Just to give some context, `dotnet tool install --global wix --version 5.0.2` installs WiX Toolset. Though the way WiX implements its own distribution, it does not cover WiX own extensions like WixToolset.UI.wixext. Meaning that any missing extensions need to be added as extra.

WixSharp tries to improve user experience and attempts to install the extension if it's not found during the build. If, for whatever reason, it cannot install the extension programmatically, then it advises the user to do it manually.

This is how you can test it:

```c#
WixExtension.UI.PreferredVersion = "99.0.0"; // indicate that we want to use the version that does not exist
project.BuildMsi();
```

This will yield:

![Image](https://github.com/user-attachments/assets/de148ce4-4302-43fc-a6c9-28e9c120ba1c)

And this is exactly what you did and it solved the problem.

> ...it kept complaining about the "PostBuild" tag in the csproj file which I believe tells ...

This is the build event that simply executes the exe you built with VS.

![Image](https://github.com/user-attachments/assets/6f23d959-e8f4-4554-949e-14c6b442d80d)

I do not expect the error message to contain any mention of a `"PostBuild" tag`. Can you share the error message please?

**Comment by TimLudwig5400** [comment]
well all I did was install the 5.0.2 wix toolset and then added your extension for the project templates and created a project with this template:

<img width="747" alt="Image" src="https://github.com/user-attachments/assets/faf8fbc1-80e1-4995-a884-f97f0cdda9f9" />

I only used your default code that comes with the project. I had the same thing happen on my laptop and my work desktop so obviously this should be in the instructions to set this up if it happens every time since I did on two separate computers and followed all the instructions on how to install everything.

By the way that top error was not the error I got (the one you are showing a screenshot). I got the second error in your screenshot, the cd .\ set ide=true. when I clicked on it it went right to the csproj file and that line for the postaction event.

<img width="563" alt="Image" src="https://github.com/user-attachments/assets/9b8a10c3-774a-43bb-8a17-a10cce4410d1" />

This all got fixed once I ran the command line for the wixext.

**Comment by oleg-shilo** [comment]
> ...obviously this should be in the instructions...

Correct. And that error message in the build output is that instruction. Thus if it was not printed, then it means that the algorithm for injecting it sometimes does not work. It would be great if I could investigate it further to see how to fix it.

Is it possible for you to find an environment where you still experience the very same problem so you can give me some details I need for the fix?

**Comment by TimLudwig5400** [comment]
> > ...obviously this should be in the instructions...
> 
> Correct. And that error message in the build output is that instruction. Thus if it was not printed, then it means that the algorithm for injecting it sometimes does not work. It would be great if I could investigate it further to see how to fix it.
> 
> Is it possible for you to find an environment where you still experience the very same problem so you can give me some details I need for the fix?

I do have another Laptop I can try it on. I will attempt to duplicate the error on there when I have a little bit of time.

**Comment by chuongmep** [comment]
I have same issue today and just resolve by using olderversion 
```
steps:
- task: PowerShell@2
  displayName: 'Install WiX Toolset'
  inputs:
    targetType: 'inline'
    script: |
      dotnet tool install --global wix --version 5.0.2
      wix extension add -g WixToolset.UI.wixext/5.0.2
```

**Comment by oleg-shilo** [comment]
Great, thank you.

Can you please share with me this:

- your build output after you enable verbose output:
  ```c#
  Compiler.VerboseOutput = true;
  project.BuildMsi();
  ```
- structure/content of your `C:\Users\<user>\.wix\extensions\WixToolset.UI.wixext`. This is what I have:
  ![Image](https://github.com/user-attachments/assets/ef328c21-0460-427b-b995-e4673ded0119)

This can give me a clue. 
BTW I can build OK with the same tool versions. So meoething is not right.

![Image](https://github.com/user-attachments/assets/6d378977-d35d-4598-b543-58d26de9aff3)

**Comment by chuongmep** [comment]
Hi @oleg-shilo , I'm using `5.0.2+aa65968c`

**Comment by oleg-shilo** [comment]
@chuongmep, great, 

Can you please share the information I asked in my prev post?

**Comment by chuongmep** [comment]
Hi @oleg-shilo I'm a different user have issue with Azure Devops, My issue may be different with the guy using.wix file

**Comment by oleg-shilo** [comment]
😄 
I know.
But you wrote, "I have same issue today and just resolve by using olderversion" so I was hoping you still have the faulty system and I can "have a look" at it by you collecting for me some info. 

Not a problem. Let's wait fro the OP to respond

**Comment by chuongmep** [comment]
> 😄 I know. But you wrote, "I have same issue today and just resolve by using olderversion" so I was hoping you still have the faulty system and I can "have a look" at it by you collecting for me some info.
> 
> Not a problem. Let's wait fro the OP to respond

Ah yes, the issue is my local computer working fine, just is problem with Azure Devops. Which one I can help to recreate the issue ?
