### ISSUE TITLE
Bootstrapper does not show license screen

### ISSUE THREAD

**Issue by ltemimi** [oleg-shilo/wixsharp#679]

**Comment by ltemimi** [comment]
Hi

I have a bootstrapper app that works well; runs the MSIs but does not show the license screen. Please help I need the MSIs screens to be shown the same as and when they are individually run. Thanks

```
 public static void Main()
        {
            var (windowsServiceInstaller, licenseWizardInstaller, iconPath) = Compile();
            var (activeConfiguration, version) = GetConfigAndVersion(windowsServiceInstaller);

            var bootstrapper =
                new Bundle("LogLogix",
                    new PackageGroupRef("NetFx40Web"),
                    new MsiPackage(windowsServiceInstaller) {DisplayInternalUI = false, Visible = true},
                    new MsiPackage(licenseWizardInstaller) {DisplayInternalUI = false, Visible = true})
                {
                    Version = new Version(version),
                    UpgradeCode = new Guid("{C7278B04-2933-4429-8858-3F9A382FF88E}"),
                    IconFile = iconPath,
                    Manufacturer = "Automation Consultancy Ltd"
                };

            bootstrapper.Build($"LogLogix_{activeConfiguration}_{version}.exe");
        }
```

**Comment by oleg-shilo** [comment]
Does `new MsiPackage(licenseWizardInstaller)` have UI? If does then is it native MSI UI or managed UI MSI UI?

**Comment by ltemimi** [comment]
Hi Oleg

Yes my MSIs have a managed UI where I customized the dialogs. 

Thanks

**Comment by oleg-shilo** [comment]
:(
This is what I was afraid of...

WiX has a long standing bug that the team is reluctant to fix. Bootstrapper fails 
to show ANY _EmbeddedUI_ (not only WixSharp).

The issue has been reported to the WiX team and they reluctantly accepted it but the bug is still not fixed. Presumably will be fixed in WiX 4.

Read the last "Why setting DisplayInternalUI to true works..." section here: https://github.com/oleg-shilo/wixsharp/wiki/Wix%23-Bootstrapper-integation-notes

**Comment by Torchok19081986** [comment]
Hallo, oleg. Unfortunatally, same problem in Bootsrapper . Do you have info if this long standing bug will be ever fixed in Wix 4 and when we could use it in Wixsharp with your help ? I found nothing about it in wixtoolset . Only this was classified as Bug. No info if fixed. Bug is knowing since 2015 or 2017. Must be some terrible hard to fix it.

**Comment by oleg-shilo** [comment]
Will need to read through. Thanks for sharing.

As for WiX team I only know that they have allocated milestone "4.0" for the fix abut have no idea about their actual backlog. 

One thing that I am sure is that the bug is not fixed yet and that v4.0 is still beta (as it was ~3-6 month ago) so I cannot test it. 

That's why I was happy when one of WixSharp users contributed `NsisBootstrapper`, which is immune to the problem.

**Comment by Torchok19081986** [comment]
just tested it project from link. works really good. It calls alle CA´s in project, install both msi`s, and install silently mysql community. Looks like ManagedBootstapper with some customization. All embeded files install complently silent and progress will be reported to bootstapper.

**Comment by oleg-shilo** [comment]
No I am not sure we are talking about the same thing. 

Your original post was about trying to show EmbeddedUI of your msi from the boostatrapper. Though you describe the potential solution as "All embeded files install complently silent... ".

What am I missing here?

**Comment by Torchok19081986** [comment]
Nothing. It was my bad. I didnt knew it was silent install, i thought i show embedui from prism and json. again, very sorry, my bad.  it looks like completly custom ui. Maybe completly customui is key for problem with bootstrapper.

**Comment by oleg-shilo** [comment]
Not a problem :)

**Comment by Torchok19081986** [comment]
Hallo, Oleg. i found something really intersting. Here in CustomBA , if i understand right and tested, Custom BA show LicenseFile.rtf. Verify it on Testsystem. Can you please view and give some feedback. If yes, i would like to start with. It exactly what i need for my mainsoftware as Bootstrapper.
https://github.com/nickguletskii/WixWPFWizardBA
